import type { Analysis, Transition } from './types';
export function escapeHtml(value: string): string {
  return value.replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char]!));
}
export function htmlReport(report: Analysis): string {
  const esc = escapeHtml;
  const label = report.status === 'loop-found' ? 'Feedback loop found in the model' : report.status === 'settles' ? 'This modeled handoff settles' : 'Incomplete rehearsal';
  const step = (edge: Transition): string => {
    const from = report.states[edge.from]!; const to = report.states[edge.to]!;
    return `<li><strong>${esc(edge.workflow)}</strong><p><code>${esc(from.resource)} · ${esc(from.event)}</code> → <code>${esc(to.resource)} · ${esc(to.event)}</code></p><pre>${esc(JSON.stringify(to.data, null, 2))}</pre></li>`;
  };
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; base-uri 'none'; form-action 'none'"><title>TriggerTangle rehearsal report</title><style>body{max-width:1000px;margin:45px auto;padding:0 25px;background:#f8faf9;color:#18303b;font:16px/1.6 system-ui,sans-serif}h1{font-size:38px;line-height:1.2}h2{margin-top:36px}li{margin:18px 0}code,pre{font-family:ui-monospace,monospace;white-space:pre-wrap;overflow-wrap:anywhere;unicode-bidi:plaintext}pre{padding:16px;background:#edf1f1;border:1px solid #c8d4d7}table{border-collapse:collapse;width:100%}td,th{border-bottom:1px solid #c8d4d7;padding:12px;text-align:left;overflow-wrap:anywhere}.notice{border-left:4px solid #b56b00;padding:10px 18px;background:#fff3d9}@media print{li{break-inside:avoid}}</style></head><body><p>TRIGGERTANGLE / DESIGN REHEARSAL</p><h1>${esc(label)}</h1><h2>${esc(report.name)}</h2><p>${esc(report.reason)}</p><p class="notice">Model evidence only. No live apps were checked or changed. Applies to one seed and the declared assumptions.</p><p>${report.stats.states} unique states · ${report.stats.transitions} transition edges · exploration ${report.complete ? 'complete' : 'incomplete'}</p><p>Modeled workflow starts: ${report.stats.workflowStarts ?? 'unavailable'} · emitted event deliveries: ${report.stats.emittedEvents ?? 'unavailable'}</p><p>Budget: ${report.budget.maxStates} states / ${report.budget.maxTransitions} edges</p>${report.witness ? `<h2>Lead-in</h2>${report.witness.leadIn.length ? `<ol>${report.witness.leadIn.map(step).join('')}</ol>` : '<p>The cycle starts at the seed signal.</p>'}<h2>Repeating chain</h2><ol>${report.witness.cycle.map(step).join('')}</ol>` : '<p>No cycle witness is available. An incomplete search cannot rule out a loop.</p>'}<h2>Assumptions and limits</h2><ul>${report.notes.map(note => `<li>${esc(note)}</li>`).join('')}</ul><h2>Modeled workflows</h2><table><thead><tr><th>Workflow</th><th>Enabled</th><th>Trigger</th></tr></thead><tbody>${report.blueprint.workflows.map(workflow => `<tr><td>${esc(workflow.name)}<br><code>${esc(workflow.id)}</code></td><td>${workflow.enabled === false ? 'No' : 'Yes'}</td><td><code>${esc(workflow.on.resource)} · ${esc(workflow.on.event)}</code></td></tr>`).join('')}</tbody></table><h2>Reproducible blueprint</h2><p>Contains resource identifiers and sample data. Review before sharing.</p><pre>${esc(JSON.stringify(report.blueprint, null, 2))}</pre></body></html>`;
}
